"""empty message

Revision ID: 0ae5002c2432
Revises: 89b154788c78
Create Date: 2018-09-25 10:33:26.425495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae5002c2432'
down_revision = '89b154788c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('time', sa.TIME(), nullable=True))
    op.add_column('event', sa.Column('weekday', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'weekday')
    op.drop_column('event', 'time')
    # ### end Alembic commands ###
