"""empty message

Revision ID: 24c271ca2fcc
Revises: f37cef37bf8c
Create Date: 2018-09-25 13:34:39.747727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c271ca2fcc'
down_revision = 'f37cef37bf8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_image_table',
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_image_table')
    # ### end Alembic commands ###
