"""empty message

Revision ID: 422de17f0602
Revises: 7dff89283d31
Create Date: 2018-08-15 16:43:33.177667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422de17f0602'
down_revision = '7dff89283d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_league_end_date'), 'league', ['end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_end_date'), table_name='league')
    # ### end Alembic commands ###
