"""empty message

Revision ID: 5208b63b54cd
Revises: 8aa19ba81c7c
Create Date: 2018-07-09 20:34:40.503421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5208b63b54cd'
down_revision = '8aa19ba81c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('other', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'other')
    # ### end Alembic commands ###
