"""empty message

Revision ID: 6659f160a5ca
Revises: f907de7584ac
Create Date: 2018-07-13 13:58:45.083243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6659f160a5ca'
down_revision = 'f907de7584ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('limit', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('event', sa.Column('participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'participants')
    op.drop_column('event', 'location')
    op.drop_column('event', 'limit')
    # ### end Alembic commands ###
