"""empty message

Revision ID: 9547bbe43cb4
Revises: e75c03117e6e
Create Date: 2018-07-12 23:45:15.188457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9547bbe43cb4'
down_revision = 'e75c03117e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_file_table',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_file_table')
    # ### end Alembic commands ###
