"""empty message

Revision ID: f37cef37bf8c
Revises: 0ae5002c2432
Create Date: 2018-09-25 11:01:15.764045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37cef37bf8c'
down_revision = '0ae5002c2432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('registration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_event_registration'), 'event', ['registration'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_registration'), table_name='event')
    op.drop_column('event', 'registration')
    # ### end Alembic commands ###
